# Generated by Django 4.1.7 on 2023-04-03 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0009_profile_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200, verbose_name='Цель')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('deadline', models.DateField(verbose_name='Дата окончания')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Время создания')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created'],
            },
        ),
    ]
