# Generated by Django 4.1.7 on 2023-04-05 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_sex'),
        ('todo_list', '0002_alter_todo_created_alter_todo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile', verbose_name='Владелец'),
        ),
    ]
