# Generated by Django 4.2.1 on 2023-06-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_alter_todo_created_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created',
            field=models.DateField(default='2023-06-22'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default='2023-06-22'),
        ),
    ]
