# Generated by Django 4.1.7 on 2023-04-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Статус'),
        ),
    ]
