# Generated by Django 4.1.7 on 2023-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
    ]
