# Generated by Django 4.1.7 on 2023-03-25 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.sex', verbose_name='Пол'),
        ),
    ]
