# Generated by Django 4.1.7 on 2023-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_sex'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, choices=[(None, 'Выберите ваш пол'), ('f', 'Женский'), ('m', 'Мужской'), ('o', 'Другой')], max_length=50, null=True, verbose_name='Пол'),
        ),
    ]
