# Generated by Django 4.1.7 on 2023-03-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_sex_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-profile.jpg', upload_to='profile_pics', verbose_name='Фото'),
        ),
    ]
