# Generated by Django 4.1.7 on 2023-03-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Никнейм'),
        ),
    ]
