# Generated by Django 4.1.7 on 2023-04-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
    ]
